### ISSUE TITLE
Grundpaket: Produktionsumgebung

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jemk#3]
Domain: hitobito.jemk.ch
(db.jemk.ch wird bereits von ihrer aktuellen Datenbank verwendet. Sobald Hitobito offiziell verwendet wird, soll diese Domain dann ebenfalls auf die Hitobito Datenbank zeigen)

Vorbereitung der produktiven Umgebung

- [x] mailkonten
- [x] composition-repo um production-branch erweitern
- [x] jenkins-job
- [x] Credentials im Cryptopus
- [x] DNS vorbereiten
- [x] APPUiO-Projekt anlegen
- [x] labels setzen
- [x] initial-setup mit cia (https://wiki.puzzle.ch/Hitobito/ProjektSetup)
- [x] kustomize-overlay
- [x] apply-config
- [x] Weiterleitung hitobito.jemk.ch -> cname.jemk.hitobito.ch 
- [x] Monitoring (https://docs.puzzle.ch/guides/latest/ruby-rails-user-guide/index.html#_monitoring_einrichten)

See: #1

**Comment by kronn** [comment]
Der Setup ist soweit abgeschlossen. Das Passwort für den Root-User lege ich noch in unsere PW-Verwaltung.
