### ISSUE TITLE
Grundpaket: Wagon erstellen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jemk#4]
Ein neuer Wagon "hitobito_jemk"

https://github.com/hitobito/hitobito/blob/master/doc/development/04_wagons.md

See: #1

**Comment by kronn** [comment]
Ich habe keinen PR gemacht, aber dennoch was im Core geändert:

[Anpassungen für wagon create](https://github.com/hitobito/hitobito/compare/d526cd2b4bc5c7f6c4353566de11fa094ee8b860...1.28.74%5E1)

Das Ergebnis ist dann https://github.com/hitobito/hitobito_jemk
