### ISSUE TITLE
Grundpaket: Mehrsprachigkeit

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jemk#7]
Gewünschte Sprachen DE, ~FR, IT, EN~ einbauen

settings.yml
transifex -> eigenes Projekt (für Wagon spezifische Übersetzungen)
Kunde berechtigen und instruieren

See: #1

**Comment by ThomasEllenberger** [comment]
Absprache mit @rafibu:

JEMK hat nur deutssprachige Jungscharen. Dessalb reicht hier Deutsch als Sprache aus.

**Comment by kronn** [comment]
Sicherstellen, dass kein transifex konfiguriert ist und alle Automatisierungen das korrekt erkennen.
